# Generated by Django 5.2.14 on 2026-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='defoult_profile_picture_pic.jpg', upload_to=''),
        ),
    ]
